const SEED_DATA = {
  platforms: ["Vinted", "Wallapop", "OLX", "CustoJusto"],
  types: ["Pulseira", "Colar", "Anel", "Brincos", "Conjunto", "Pendente"],
  conditions: ["Muito bom", "Bom", "Com sinais normais de uso", "Vintage usado", "A confirmar"],
  materials: ["prata confirmada", "prata 925 marcada", "silver tone", "metal prateado", "desconhecido"],
  styles: ["boho", "vintage", "tribal", "étnico", "hippie chic", "rock", "statement"],
  tones: ["curto", "neutro", "premium", "persuasivo", "cauteloso", "fecho de venda"],
  languages: ["Português PT", "Espanhol", "Inglês"],
  results: ["interessado", "comprou", "recusou", "negociar depois"],
  adTexts: [
    { id: "title-82g-1", kind: "titulo", platform: "Todas", category: "Pulseira 82g", favorite: true, uses: 0, text: "Pulseira Silver Tone Malha Cobra 82g", createdAt: "2026-05-08T19:30:00.000Z" },
    { id: "title-82g-2", kind: "titulo", platform: "Todas", category: "Pulseira 82g", favorite: false, uses: 0, text: "Pulseira Silver Tone Multi-Fio 82g", createdAt: "2026-05-08T19:31:00.000Z" },
    { id: "title-82g-3", kind: "titulo", platform: "Todas", category: "Vintage", favorite: false, uses: 0, text: "Pulseira Vintage Silver Tone Multi-Fio", createdAt: "2026-05-08T19:32:00.000Z" },
    { id: "title-82g-4", kind: "titulo", platform: "Todas", category: "Statement", favorite: false, uses: 0, text: "Pulseira Silver Tone com Grande Presença", createdAt: "2026-05-08T19:33:00.000Z" },
    { id: "title-82g-5", kind: "titulo", platform: "Todas", category: "Malha cobra", favorite: false, uses: 0, text: "Pulseira Cobra Multi-Fio Silver Tone", createdAt: "2026-05-08T19:34:00.000Z" },
    { id: "title-82g-6", kind: "titulo", platform: "Todas", category: "Vintage", favorite: false, uses: 0, text: "Pulseira Silver Tone Estilo Vintage", createdAt: "2026-05-08T19:35:00.000Z" },
    { id: "title-82g-7", kind: "titulo", platform: "Todas", category: "Pulseira 82g", favorite: false, uses: 0, text: "Pulseira Multi-Fio Silver Tone 82g", createdAt: "2026-05-08T19:36:00.000Z" },
    { id: "title-82g-8", kind: "titulo", platform: "Todas", category: "Trabalhada", favorite: false, uses: 0, text: "Pulseira Silver Tone Trabalhada 82g", createdAt: "2026-05-08T19:37:00.000Z" }
  ],
  listings: [
    {
      id: "seed-82g",
      title: "Pulseira Prata da Índia - 82g",
      type: "Pulseira",
      weight: 82,
      measure: "",
      material: "prata confirmada",
      confirmed: "sim",
      mark925: "não",
      style: "boho",
      condition: "Muito bom",
      platform: "Vinted",
      targetPrice: 59,
      minPrice: 49,
      status: "ativo",
      interest: 8,
      responsesSent: 5,
      proposals: 2,
      sourceUrl: "https://www.vinted.pt",
      notes: "Malha cobra multi-fio, peça robusta e pesada com presença forte.",
      description: "Pulseira estilo prata da Índia com impressionantes 82g e visual marcante em malha cobra multi-fio. Peça robusta, pesada e com excelente presença no pulso, inspirada nas pulseiras artesanais indianas vintage muito procuradas pelo seu estilo étnico/boho. Os detalhes e acabamento dão-lhe um look distinto e autêntico, ideal para quem gosta de acessórios com personalidade. Combina muito bem com estilos vintage, alternativo, rock, casual ou streetwear.",
      photos: [],
      createdAt: "2026-05-08T09:00:00.000Z",
      updatedAt: "2026-05-08T09:00:00.000Z"
    },
    {
      id: "seed-35g",
      title: "Pulseira Prata da Índia - 35g",
      type: "Pulseira",
      weight: 35,
      measure: "",
      material: "prata confirmada",
      confirmed: "sim",
      mark925: "não",
      style: "vintage",
      condition: "Muito bom",
      platform: "OLX",
      targetPrice: 39,
      minPrice: 32,
      status: "ativo",
      interest: 5,
      responsesSent: 3,
      proposals: 1,
      sourceUrl: "https://www.vinted.pt",
      notes: "Pulseira de malha cobra multi-fio, confortável no pulso.",
      description: "Pulseira estilo prata da Índia com malha cobra multi-fio e excelente presença no pulso. Peça robusta com 35g, acabamento detalhado e visual vintage/étnico muito marcante. Inspirada nas joias artesanais indianas, combina facilmente com looks boho, alternativos, rock, casual ou streetwear. Muito confortável no pulso e com ótimo impacto visual.",
      photos: [],
      createdAt: "2026-05-08T09:05:00.000Z",
      updatedAt: "2026-05-08T09:05:00.000Z"
    },
    {
      id: "seed-colar-95g",
      title: "Colar Prata da Índia - 48 cm - 95g",
      type: "Colar",
      weight: 95,
      measure: 48,
      material: "prata confirmada",
      confirmed: "sim",
      mark925: "não",
      style: "étnico",
      condition: "Muito bom",
      platform: "CustoJusto",
      targetPrice: 79,
      minPrice: 65,
      status: "pausado",
      interest: 10,
      responsesSent: 7,
      proposals: 3,
      sourceUrl: "https://www.vinted.pt",
      notes: "Colar pesado, malha cobra, forte impacto visual.",
      description: "Colar estilo prata da Índia com impressionantes 95g e malha cobra de forte impacto visual. Peça robusta e marcante, inspirada nas joias artesanais indianas vintage, com excelente presença ao usar. O acabamento e textura da malha dão-lhe um visual étnico/boho muito procurado atualmente, funcionando tanto em looks casuais como alternativos ou mais sofisticados.",
      photos: [],
      createdAt: "2026-05-08T09:10:00.000Z",
      updatedAt: "2026-05-08T09:10:00.000Z"
    }
  ],
  responseLibrary: [
    { id: "auth-1", category: "autenticidade", lang: "Português PT", tone: "neutro", uses: 4, favorite: true, text: "A peça foi confirmada como prata por ourives após a compra. Não vejo marcação 925 visível, por isso prefiro descrevê-la exatamente dessa forma." },
    { id: "auth-2", category: "autenticidade", lang: "Português PT", tone: "premium", uses: 2, favorite: true, text: "Tem bastante peso e presença ao vivo. A peça foi confirmada como prata por ourives depois da compra, embora não tenha marcação visível 925." },
    { id: "disc-1", category: "desconto", lang: "Português PT", tone: "persuasivo", uses: 5, favorite: false, text: "Posso ajustar um pouco o valor, mas como é uma peça pesada e com bastante procura não consigo baixar muito mais." },
    { id: "res-1", category: "reserva", lang: "Português PT", tone: "neutro", uses: 1, favorite: false, text: "Posso reservar durante algum tempo, mas tenho tido bastante interesse nesta peça." },
    { id: "disp-1", category: "disponibilidade", lang: "Português PT", tone: "curto", uses: 6, favorite: true, text: "Sim, continua disponível." },
    { id: "urg-1", category: "urgência suave", lang: "Português PT", tone: "fecho de venda", uses: 3, favorite: false, text: "Este tipo de peças costuma sair relativamente rápido, sobretudo as mais pesadas." },
    { id: "cross-1", category: "cross-sell", lang: "Português PT", tone: "neutro", uses: 2, favorite: false, text: "Tenho outras pulseiras/colares semelhantes no perfil caso queira combinar várias peças." },
    { id: "ship-1", category: "envio", lang: "Português PT", tone: "curto", uses: 4, favorite: false, text: "Sim, envio normalmente através da Vinted/Wallapop sem problema." }
  ],
  conversations: [
    {
      id: "conv-seed-1",
      buyer: "Comprador Vinted",
      platform: "Vinted",
      question: "Ainda está disponível? É prata?",
      response: "Sim, continua disponível. A peça foi confirmada como prata por ourives após a compra.",
      listingId: "seed-82g",
      category: "autenticidade",
      result: "interessado",
      createdAt: "2026-05-08T10:00:00.000Z"
    }
  ]
};
